"""Add detailed profiles and measurement tracking

Revision ID: 4b053c7c3981
Revises: 2b2c2dc2422f
Create Date: 2025-07-04 17:14:25.551251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b053c7c3981'
down_revision = '2b2c2dc2422f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Float(), nullable=True),
    sa.Column('bone_mass_kg', sa.Float(), nullable=True),
    sa.Column('visceral_fat_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('injuries', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('objective', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('intensity', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('intensity')
        batch_op.drop_column('objective')
        batch_op.drop_column('injuries')
        batch_op.drop_column('gender')
        batch_op.drop_column('date_of_birth')

    op.drop_table('body_measurements')
    # ### end Alembic commands ###
